### ISSUE TITLE
Sound plugin seems to be missing

### ISSUE THREAD

**Issue by DippyDoo** [bitcraft/PURIKURA#1]
I am trying to get PuriKura working on my Linux Mint system.  

When I try to execute pbtether.py in the root folder, it looks to load the "sound" plugin from the Pyrikura/plugin folder. The problem is there is no "sound" plugin in that folder.

Am I missing something or is the upload actually missing the "sound" plugin?

p.s Could you please throw in a quick primer on how to get PURIKURA working.

**Comment by bitcraft** [comment]
So sorry that I haven't replied until now.  With the holidays and extra work, I've just been totally swamped!  I'll check my local repo tonight and make sure it is current.  I'll add a how-to on the wiki...check it out next week.  Thanks for your interest.

**Comment by bitcraft** [comment]
I updated the wiki and also added some files i forgot to commit.
