### ISSUE TITLE
pbtether.py missing

### ISSUE THREAD

**Issue by glennikin** [bitcraft/PURIKURA#2]
Hi there,

Having a go at getting this to run on Debian 7.3. It seems pbtether.py is missing from the file repository. When I execute the run.sh script with my camera attached, all I get is the galaxy background and a white square haha!

Many thanks for sharing this.

Glenn

**Comment by bitcraft** [comment]
Yikes!  Thanks for letting me know.  I’ll get that up right away.  What camera are you using btw?

**Comment by bitcraft** [comment]
I've made sure that everything is up to date.  Please make sure you are using the latest commit, since pbtether.py shouldn't be in use anymore.  The galaxy background is the standard background.  You won't see anything on it until pictures are taken and processed.

**Comment by glennikin** [comment]
Ah, I understand, good stuff. I'm using a Canon EOS 1100D with Debian at the moment, but I also have a Canon EOS 7D to hand.

Thanks for the very quick reply!
